### ISSUE TITLE
Consider adding an open license

### ISSUE THREAD

**Issue by kelly-sovacool** [umangv/thesis-umich#2]
Hi @umangv,

Would you consider adding a [Creative Commons](https://creativecommons.org/about/cclicenses/) or [OSI](https://opensource.org/licenses) License to this repo? I'm hoping to fork and adapt it to make a Quarto template, and want to be sure I have permission to do so.

We may also want to reach out to Derek Dalle (@derek-dalle / @nasa-ddalle?) since he converted `rac.sty` to the original `thesis-umich.cls`.

**Comment by nasa-ddalle** [comment]
I support adding the CC0, Creative Commons License releasing to the public domain
